# Steps to Create a GitHub Repository and Upload Your Rust Project

1. **Create a GitHub account** if you don't already have one at https://github.com/

2. **Create a new repository**:
    - Click the "+" icon in the top right corner
    - Select "New repository"
    - Name it (e.g., "orng-rust")
    - Add a description (optional)
    - Choose public or private
    - Click "Create repository"

3. **Initialize git in your local project**:
    ```
    cd /home/bun/orng-rust
    git init
    ```

4. **Create a .gitignore file** for Rust:
    ```
    curl -s https://raw.githubusercontent.com/github/gitignore/master/Rust.gitignore -o .gitignore
    ```

5. **Add your files and commit**:
    ```
    git add .
    git commit -m "Initial commit"
    ```

6. **Connect to the remote repository**:
    ```
    git remote add origin https://github.com/YOUR-USERNAME/orng-rust.git
    ```

7. **Push your code**:
    ```
    git push -u origin main
    ```
    (Use `master` instead of `main` if your default branch is named "master")

8. **Create a README.md file** (optional but recommended):
    ```
    echo "# ORNG Rust" > README.md
    git add README.md
    git commit -m "Add README"
    git push
    ```

Your Rust project should now be uploaded to GitHub!
